name: Commit File to Another Repository

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Create and Commit File
        run: |
          echo "Hello, World!" > newfile.txt  # Replace with your file content and name.
          git add newfile.txt
          git commit -m "Add newfile.txt via GitHub Action"

      - name: Push changes
        env:
          TARGET_REPO_URL: https://github.com/SachinP/SpringWithSonor.git  # Replace with your target repository URL
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Automated push by GitHub Actions"
          git push ${{ secrets.GITHUB_TOKEN }} HEAD:master
